version: '3'

services:

  app:
    build: .
    container_name: esquenta-4-frontend
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    tty: true